select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, round(precio) from producto;
select codigo_fabricante from producto;
select codigo_fabricante from producto group by codigo_fabricante;
select nombre from fabricante order by nombre asc;
select nombre from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from producto order by precio limit 1;
select * from producto order by precio desc limit 1;
select * from producto where precio between 0 and 120 ;
select * from producto where precio between 60 and 200 ;
select * from producto where codigo_fabricante in (1,3,5);
select * from producto where nombre like '%portatil%';
select p.codigo, p.nombre, f.codigo, f.nombre from producto p,fabricante f where f.codigo=p.codigo_fabricante;
select p.codigo, p.nombre, p.codigo_fabricante, f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo order by f.nombre;
select p.codigo, p.nombre, p.codigo_fabricante, p.precio, f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo order by p.precio limit 1;
select p.*, f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo where f.nombre like '%lenovo%';
select p.*, f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo where f.nombre like '%crucial%' and p.precio > 200;
select p.*, f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo where f.nombre in ('asus','hewlett-packard');
select p.nombre,p.precio,f.nombre from producto p inner join fabricante f on p.codigo_fabricante=f.codigo where p.precio > 180 order by p.precio desc, p.nombre asc;
select f.nombre,p.nombre from fabricante f left join producto p on f.codigo=p.codigo_fabricante;
select f.nombre,p.nombre from fabricante f left join producto p on f.codigo=p.codigo_fabricante where p.nombre is null;
select f.nombre,p.nombre from fabricante f, producto p where f.codigo=p.codigo_fabricante and f.nombre in (select nombre from fabricante where nombre like 'Lenovo');
select f.nombre,p.* from fabricante f, producto p where f.codigo=p.codigo_fabricante and p.precio = (select max(p.precio)from producto p, fabricante f where p.codigo_fabricante=f.codigo and f.nombre like 'Lenovo' );
select p.nombre from producto p inner join fabricante f on f.codigo=p.codigo_fabricante where p.precio=(select max(p.precio) from producto p inner join fabricante f on  p.codigo_fabricante=f.codigo where f.nombre like 'Lenovo');
select p.* from producto p inner join fabricante f on f.codigo=p.codigo_fabricante where f.nombre like 'Asus' and p.precio> (select avg(precio) from producto);
select nombre from fabricante where nombre in (select f.nombre from fabricante f inner join producto p on p.codigo_fabricante=f.codigo);
select nombre from fabricante where nombre not in (select f.nombre from fabricante f inner join producto p on p.codigo_fabricante=f.codigo);
select f.nombre  from producto p, fabricante f where f.codigo = p.codigo_fabricante group by p.codigo_fabricante having count(p.codigo_fabricante) = ( select count(p.codigo_fabricante)  from tienda.producto p, tienda.fabricante f where f.codigo = p.codigo_fabricante and   f.nombre = 'Lenovo' group by p.codigo_fabricante);
